# Generated by Django 6.0.2 on 2026-02-10 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kirim narxi (1 dona)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Kirim miqdori')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Umumiy summa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
