# Generated by Django 6.0.2 on 2026-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_expense_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
